server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    webclient:
       enabled: true
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8070/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
 
spring:
  cloud:
    loadbalancer: 
       configurations: health-check # Required for enabling SDC with health checks
    gateway:
        httpclient:
            wiretap: true
        routes:
           - id: organization-service
             uri: lb://organization-service
             predicates:
                - Path=/organization/**
             filters:
                - RewritePath=/organization/(?<path>.*), /$\{path}
           - id: licensing-service
             uri: lb://licensing-service
             predicates:
                - Path=/license/**
             filters:
                - RewritePath=/license/(?<path>.*), /$\{path}
                - RemoveRequestHeader= Cookie,Set-Cookie

       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        